= Literature Review

China's Social Credit System has garnered significant interest from scholars for its novel governance approach. Initial research examined the system's original function, which was to alleviate financial fraud and distrust, by providing centralized features to help assess someone's trustworthiness. Subsequent research has shown how the SCS has evolved into a holistic system that assesses credibility not only for economic purposes but for compliance with laws and regulations, social behavior, and administrative integrity, highlighting its role in reinforcing common societal normative behaviors and state control.

Empirical studies underscore the operational fragmentation of the SCS. Engelmann et al. @engelmann_blacklists_2021 conducted the first comprehensive analysis of Blacklists and Redlists across 30 provincial-level ADs in 2019, uncovering substantial regional disparities in list diversity and implementation approaches. Their research highlighted that Blacklists predominantly targeted "Dishonest Debtors," aiming to transform "Lao Lai" into compliant entities through restrictive measures. In contrast, Redlists lacked a specific focus, primarily incentivizing commendable behavior. The authors expressed concern over the potential evolution of the SCS into a broader social control mechanism if its development extended beyond its legal framework.

Dang @dang_data-driven_2023 extended this work in a 2023 Master's thesis, examining the SCS's progression since 2019. The study identified a trend toward list consolidation by analyzing variations in the number of lists on AD credit pages and comparing entry detail levels to earlier datasets. While unified lists retained specific category information within entries, they observed inconsistent changes in information detail for both "Dishonest Debtors" Blacklists and "Class A Taxpayer" Redlists, reinforcing the system's fragmented regional development. Although this cross-comparative study revealed critical insights, it omitted a deeper analysis of the institutional structures governing the lists.

Policy analyses further illuminate structural tensions driving regional variation. Tsai et al. @tsai_hobbling_2021 argue that China's policy implementation operates under a "top-level design" framework, where the central government outlines broad blueprints and delegates detailed regulation development to local officials through trial-and-error processes. This discretionary approach often leads officials to prioritize less politically sensitive objectives, such as promoting business integrity over civil servant or public integrity, to minimize backlash. The authors emphasize that ambiguous central directives and localized discretion significantly fragment SCS practices across regions. On the other hand, the MERICS China Monitor report @drinhausen_chinas_2022 discusses a different trend from fragmentation to integration. The report shows that the 14th Five-Year Plan (2021-2025) @creemers_14th_nodate prioritized the strengthening of regulation; this provides a legal footing for the SCS as well as a way to deepen integration into the governance framework based on standardized data collection and enforcement processes. Together, these perspectives show that the SCS is currently undergoing a shift from a fragmented setup to a more consistent and unified system.

Despite these advances, gaps persist in understanding post-2023 developments, particularly as the 14th Five-Year Plan concludes and the first Social Credit Law @noauthor_law_2022 nears implementation. This study builds on prior foundations by examining how list changes and institutional hierarchies shape the SCS, offering updated insights into this ever-evolving governance model.