#import "utils.typ": todo

= Introduction <chapter_introduction>

"To govern a country, it is necessary first to regulate the family," proclaimed Confucius two millennia ago, emphasizing that governance begins with personal and local responsibility, extending outward to society. This principle finds new resonance in China's Social Credit System (SCS), where local authorities play a central role in quantifying trustworthiness and regulating behavior to ensure societal harmony. Frequently misunderstood and often labeled as a mechanism for a unified surveillance state, the SCS is, in reality, a fragmented system implemented heterogeneously across China's Administrative Divisions (AD). Local governments adapt their application to address regional priorities, resulting in diverse approaches to its implementation.

The SCS was introduced in 2014 as part of China's "Planning Outline for the Construction of a Social Credit System (2014-2020)" @noauthor_establishment_2015. This foundational policy aimed to formalize trustworthiness assessments across economic, judicial, and administrative domains. While initially focused on financial trustworthiness, it has since developed into a complex governance framework coordinating central directives with localized enforcement across four pillars: businesses, citizens, social organizations, and government entities @drinhausen_chinas_2022. 

The system's scope expanded significantly under the 13th Five-Year Plan (2016-2020), which emphasized the integration of credit data across various sectors and piloted regional implementations @drinhausen_chinas_2022. The 14th Five-Year Plan (2021-2025) continues this trajectory, highlighting the necessity to accelerate the development of the credit system as part of broader efforts to modernize governance through standardization and cooperation between regions, as evidenced by the "Action Plan for the Establishment of the Social Credit System" for 2024-2025 @noauthor_2024-2025_2024.

A key milestone during this period is the draft of the "Law of the People's Republic of China on the Establishment of the Social Credit System," @noauthor_law_2022, released in 2022. This law will define the legal foundations of the SCS for the first time, standardize definitions of trustworthiness, clarify enforcement mechanisms, and establish unified oversight under the National Development and Reform Commission (NDRC) and the People's Bank of China (PBOC). While the "Action Plan for the Establishment of the Social Credit System" for 2024-2025 calls for an acceleration of the introduction of the law, no official timeline for adoption has been announced, and the draft remains under legislative review as of April 2025. At the same time, our analysis of Blacklists and Redlists reveals that tensions persist between the ambitions of central standardization and the realities of regional implementation.

At the heart of the SCS are Blacklists and Redlists, which serve as essential tools for rewarding or penalizing entities based on their assessed trustworthiness. For instance, a blacklisted business will have limited eligibility for financial assistance from the government. At the same time, a redlisted one with a strong reputation for trustworthiness might gain expedited access to loans and other economic benefits @schaefer_chinas_2020. Despite their centrality to the system, little attention has been paid to how these lists are structured and managed across different regions.

While previous research @dang_data-driven_2023 has compared Blacklists and Redlists between 2019 and 2023, this thesis extends the analysis by focusing on list data collected from 23 ADs from 2024 - 2025. By comparing our latest results against data from 2023, this study shows what has remained consistent and what has changed in the practical application of the SCS. It provides a detailed examination of list structures, demographic targeting, and institutional frameworks, offering a more thorough understanding of regional variations within the SCS. The thesis addresses three key research questions: 

_1. How do implementation patterns of Blacklists and Redlists vary across China's ADs?_

_2. What institutional structures govern the administration of these lists?_

_3. To what extent has standardization progressed between 2023 and 2025?_

By documenting and analyzing these structural and institutional aspects of the SCS, this thesis provides an essential empirical foundation for future research. It establishes a baseline understanding of the system's operational dynamics, capturing patterns of convergence toward national standards alongside persistent regional divergence. The findings offer a valuable resource for subsequent studies to further explore questions about policy effectiveness and the broader societal implications of China's experiment in data-driven governance.