#import "utils.typ": todo

= Discussion and Conclusion

China's strategic emphasis on data-driven governance, particularly through the SCS, reveals a complex interplay between central standardization policies and varying regional implementation practices. While national policies like the 2024-2025 Action Plan @noauthor_2024-2025_2024 demonstrate efforts to unify the system, our analysis of Blacklist/Redlist administration across 23 ADs reveals persistent structural fragmentation that aligns with broader critiques of China's data governance framework and its current state of fragmentation and lack of standardization @he_state-centric_2023. 
The differences we observe in list implementations mainly stem from three main factors:

1. *Ambiguous Top-Level Design:* Central authorities issue broadly defined policy directives while delegating specific implementation to local governments. This combination of vague central guidance and local discretion often creates confusion among government officials on how to implement the policies @tsai_hobbling_2021, enabling ADs like Inner Mongolia (97.3% Redlist focus) and Tibet (100% Blacklist focus) to develop opposed implementation strategies while technically complying with national guidelines. 
2. *Multilayered Administrative Hierarchy:* China's complex administrative structure-spanning national, provincial, prefectural, and county levels creates significant variation in how regions distribute authority for managing Blacklists and Redlists. Some ADs concentrate list management at higher administrative levels, while others delegate these responsibilities to lower, more localized authorities.
3. *Data Silos and Access Restrictions:* The system of vertically managed authorities possibly leads to information asymmetries due to the "unwillingness to release data" between departments noted in prior research @tsai_hobbling_2021. 

Despite these dissimilarities, our findings confirm partial success in national consolidation efforts, as the number of lists has decreased in almost 80% of ADs, indicating a move towards fewer and more standardized lists. However, the information detail within the list entries still varies considerably across ADs, especially Blacklists, signaling specific regional implementation differences. 

While providing novel information on 2024-2025 implementations of Blacklists and Redlists in the SCS, the thesis faces three constraints. 8 ADs remained inaccessible during the data collection period, though recent Yunnan access suggests improved future data collection possibilities. Furthermore, comparisons rely on an incomplete 2023 dataset, only allowing a partial comparison with the 2024-2025 dataset. Lastly, inconsistent authority reporting may have resulted in a misleading representation of macro-level authority distributions in the SCS. 

Nonetheless, this thesis establishes an important empirical foundation for further understanding China's Social Credit System as a hybrid governance model - unified through national policy yet differentiated by local adaptions. By documenting regional variations in Blacklist and Redlist implementation between 2024 and 2025, this study reveals both discernible progress in standardization and persistent fragmentation arising from the ongoing discrepancies between centralization and regional autonomy. These findings establish a strong foundation for future research into China's changing environment of data-driven governance.